spring:
  application:
    name: ingestion-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

      properties:
        enable.idempotence: true
        acks: all
        retries: 2147483647
        max.in.flight.requests.per.connection: 5

app:
  kafka:
    topics:
      sensor-readings:
        name: iot.sensor-readings.v1
        partitions: 3
        replication-factor: 1
        retention: 3d

      rejected-sensor-messages:
        name: iot.sensor-readings.invalid.v1
        partitions: 3
        replication-factor: 1
        retention: 7d

  mqtt:
    broker-url: ${MQTT_BROKER_URL:tcp://localhost:1883}
    client-id: ${MQTT_CLIENT_ID:ingestion-service}
    topic: iot/+/+/+/+/+/readings
    qos: 1
    connection-timeout-seconds: 10
    keep-alive-seconds: 30

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - integrationgraph

  endpoint:
    health:
      probes:
        enabled: true
      show-details: always